### ISSUE TITLE
Ports are not exposed.

### ISSUE THREAD

**Issue by julioflima** [accetto/xubuntu-vnc-novnc#4]
I have to expose the ports by -p to make work.

**Comment by accetto** [comment]
Hello juloko,

the ports are exposed by the following statement in the Dockerfile:

```Dockerfile
EXPOSE ${VNC_PORT} ${NO_VNC_PORT}
```

However, usually you use the `-P` or `-p` switches with the `docker run` command to bind them to some **free** TCP ports on your host system. Usually I prefer the `-P` switch, which binds **all** ports exposed by the container to the first free ports on the host system.

Cheers,
accetto

**Comment by julioflima** [comment]
Sorry, only after I realized this. Thanks for explain everything so well.
